---

- set_fact:
    www_user: www-data
    apache_svc: apache2
    apache_confdir: /etc/apache2/conf-available
    apache_sitedir: /etc/apache2/sites-available
    apachesslconf: /etc/apache2/sites-enabled/default-ssl.conf
    apache_logdir: /var/log/apache2
    modsecurity_conf: /etc/modsecurity/modsecurity.conf
    modsecurity_active: /usr/share/modsecurity-crs/activated_rules
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- set_fact:
    www_user: apache
    apache_svc: httpd
    apache_confdir: /etc/httpd/conf.d
    apache_sitedir: /etc/httpd/conf.d
    apachesslconf: /etc/apache2/sites-enabled/default-ssl.conf
    apache_logdir: /var/log/httpd
    modsecurity_conf: /etc/httpd/conf.d/mod_security.conf
    modsecurity_active: /etc/httpd/modsecurity.d/activated_rules
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

